# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1108, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 20, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtKeyMatrix = QtWidgets.QTextEdit(self.centralwidget)
        self.txtKeyMatrix.setGeometry(QtCore.QRect(170, 80, 301, 61))
        self.txtKeyMatrix.setObjectName("txtKeyMatrix")
        self.btnCreateMatrix = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreateMatrix.setGeometry(QtCore.QRect(490, 80, 75, 23))
        self.btnCreateMatrix.setObjectName("btnCreateMatrix")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 160, 421, 251))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_4.setObjectName("label_4")
        self.txtPlainText = QtWidgets.QTextEdit(self.groupBox)
        self.txtPlainText.setGeometry(QtCore.QRect(70, 10, 311, 101))
        self.txtPlainText.setObjectName("txtPlainText")
        self.txtEncryptKey = QtWidgets.QTextEdit(self.groupBox)
        self.txtEncryptKey.setGeometry(QtCore.QRect(70, 120, 311, 91))
        self.txtEncryptKey.setObjectName("txtEncryptKey")
        self.btnEncrypt = QtWidgets.QPushButton(self.groupBox)
        self.btnEncrypt.setGeometry(QtCore.QRect(160, 220, 75, 23))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 160, 441, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_6.setObjectName("label_6")
        self.txtCipherText = QtWidgets.QTextEdit(self.groupBox_2)
        self.txtCipherText.setGeometry(QtCore.QRect(80, 10, 311, 101))
        self.txtCipherText.setObjectName("txtCipherText")
        self.txtDecryptKey = QtWidgets.QTextEdit(self.groupBox_2)
        self.txtDecryptKey.setGeometry(QtCore.QRect(80, 120, 311, 91))
        self.txtDecryptKey.setObjectName("txtDecryptKey")
        self.btnDecrypt = QtWidgets.QPushButton(self.groupBox_2)
        self.btnDecrypt.setGeometry(QtCore.QRect(180, 220, 75, 23))
        self.btnDecrypt.setObjectName("btnDecrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1108, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PLAYFAIR CIPHER"))
        self.label_2.setText(_translate("MainWindow", "TẠO MA TRẬN KHÓA :"))
        self.btnCreateMatrix.setText(_translate("MainWindow", "Tạo ma trận"))
        self.groupBox.setTitle(_translate("MainWindow", "Mã Hoá"))
        self.label_3.setText(_translate("MainWindow", "Plain text"))
        self.label_4.setText(_translate("MainWindow", "Key "))
        self.btnEncrypt.setText(_translate("MainWindow", "ENCRYPT"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Giải Mã"))
        self.label_5.setText(_translate("MainWindow", "Cipher text"))
        self.label_6.setText(_translate("MainWindow", "Key "))
        self.btnDecrypt.setText(_translate("MainWindow", "DECRYPT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
